import React from "react";
import { CardList } from "../components";
export default {
  title: "CardList",
  component: CardList,
  argTypes: {
    filter: {
      options: ["all", "featured", "popular"],
      control: { type: "radio" },
    },
    datas: {
      options: [
        [
          {
            text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
            image: "https://picsum.photos/200/300",
            title: "Baslik",
            link: "furkanguler.com",
            linkText: "Linke Tikla",
            titleColor: "primary",
            textColor: "success",
            linkColor: "info",
            radius: "0",
            linkIsButton: false,
            popularity: false,
          },
          {
            text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
            image: "https://picsum.photos/200/300",
            title: "Baslik",
            link: "furkanguler.com",
            linkText: "Linke Tikla",
            titleColor: "primary",
            textColor: "success",
            linkColor: "info",
            radius: "0",
            linkIsButton: false,
            popularity: false,
          },
          {
            text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
            image: "https://picsum.photos/200/300",
            title: "Baslik",
            link: "furkanguler.com",
            linkText: "Linke Tikla",
            titleColor: "primary",
            textColor: "success",
            linkColor: "info",
            radius: "0",
            linkIsButton: false,
            popularity: false,
          },
        ],
        [
          {
            text: "1lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
            image: "https://picsum.photos/200/300",
            title: "Baslik",
            link: "furkanguler.com",
            linkText: "Linke Tikla",
            titleColor: "primary",
            textColor: "success",
            linkColor: "info",
            radius: "0",
            linkIsButton: false,
            popularity: false,
          },
          {
            text: "1lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
            image: "https://picsum.photos/200/300",
            title: "Baslik",
            link: "furkanguler.com",
            linkText: "Linke Tikla",
            titleColor: "primary",
            textColor: "success",
            linkColor: "info",
            radius: "0",
            linkIsButton: false,
            popularity: false,
          },
          {
            text: "1lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
            image: "https://picsum.photos/200/300",
            title: "Baslik",
            link: "furkanguler.com",
            linkText: "Linke Tikla",
            titleColor: "primary",
            textColor: "success",
            linkColor: "info",
            radius: "0",
            linkIsButton: false,
            popularity: false,
          },
        ],
      ],
      control: { type: "array" },
    },
  },
};
const Template = (args) => <CardList {...args} />;
export const Primary = Template.bind({});
Primary.args = {
  datas: [
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: true,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: true,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: true,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: true,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: true,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: false,
    },
    {
      text: "lorem ipsum dolor sit amet bla bla kar ile dunyayi gezin kanka",
      image: "https://picsum.photos/200/300",
      title: "Baslik",
      link: "furkanguler.com",
      linkText: "Linke Tikla",
      titleColor: "primary",
      textColor: "success",
      linkColor: "info",
      radius: "0",
      linkIsButton: false,
      popularity: true,
    },
  ],
  filter: "all",
};
